# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(361, 308)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.boton_1 = QtWidgets.QPushButton(Form)
        self.boton_1.setGeometry(QtCore.QRect(12, 60, 80, 36))
        self.boton_1.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_1.setObjectName("boton_1")
        self.boton_parentesisAbierto = QtWidgets.QPushButton(Form)
        self.boton_parentesisAbierto.setGeometry(QtCore.QRect(270, 60, 80, 36))
        self.boton_parentesisAbierto.setStyleSheet("background-color: rgb(129, 61, 156);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_parentesisAbierto.setObjectName("boton_parentesisAbierto")
        self.boton_2 = QtWidgets.QPushButton(Form)
        self.boton_2.setGeometry(QtCore.QRect(98, 60, 80, 36))
        self.boton_2.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_2.setObjectName("boton_2")
        self.boton_3 = QtWidgets.QPushButton(Form)
        self.boton_3.setGeometry(QtCore.QRect(184, 60, 80, 36))
        self.boton_3.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_3.setObjectName("boton_3")
        self.valor = QtWidgets.QLabel(Form)
        self.valor.setGeometry(QtCore.QRect(12, 10, 338, 41))
        self.valor.setStyleSheet("background-color: rgb(143, 240, 164);\n"
"font: 63 18pt \"URW Bookman\";")
        self.valor.setText("")
        self.valor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valor.setIndent(0)
        self.valor.setObjectName("valor")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(8, 10, 338, 41))
        self.label_2.setStyleSheet("background-color: rgb(143, 240, 164);\n"
"font: 63 18pt \"URW Bookman\";")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.boton_C = QtWidgets.QPushButton(Form)
        self.boton_C.setGeometry(QtCore.QRect(184, 187, 81, 36))
        self.boton_C.setStyleSheet("background-color: rgb(255, 163, 72);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_C.setObjectName("boton_C")
        self.boton_AC = QtWidgets.QPushButton(Form)
        self.boton_AC.setGeometry(QtCore.QRect(184, 228, 80, 36))
        self.boton_AC.setStyleSheet("background-color: rgb(255, 163, 72);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_AC.setObjectName("boton_AC")
        self.boton_9 = QtWidgets.QPushButton(Form)
        self.boton_9.setGeometry(QtCore.QRect(184, 144, 79, 36))
        self.boton_9.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_9.setObjectName("boton_9")
        self.boton_punto = QtWidgets.QPushButton(Form)
        self.boton_punto.setGeometry(QtCore.QRect(270, 144, 80, 36))
        self.boton_punto.setStyleSheet("background-color: rgb(129, 61, 156);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_punto.setObjectName("boton_punto")
        self.boton_divicion = QtWidgets.QPushButton(Form)
        self.boton_divicion.setGeometry(QtCore.QRect(98, 228, 80, 36))
        self.boton_divicion.setStyleSheet("background-color: rgb(165, 29, 45);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_divicion.setObjectName("boton_divicion")
        self.boton_4 = QtWidgets.QPushButton(Form)
        self.boton_4.setGeometry(QtCore.QRect(12, 102, 80, 36))
        self.boton_4.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_4.setObjectName("boton_4")
        self.boton_menos = QtWidgets.QPushButton(Form)
        self.boton_menos.setGeometry(QtCore.QRect(12, 270, 80, 36))
        self.boton_menos.setStyleSheet("background-color: rgb(165, 29, 45);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_menos.setObjectName("boton_menos")
        self.boton_multiplica = QtWidgets.QPushButton(Form)
        self.boton_multiplica.setGeometry(QtCore.QRect(12, 228, 80, 36))
        self.boton_multiplica.setStyleSheet("background-color: rgb(165, 29, 45);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_multiplica.setObjectName("boton_multiplica")
        self.boton_0 = QtWidgets.QPushButton(Form)
        self.boton_0.setGeometry(QtCore.QRect(98, 186, 80, 36))
        self.boton_0.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_0.setObjectName("boton_0")
        self.boton_salir = QtWidgets.QPushButton(Form)
        self.boton_salir.setGeometry(QtCore.QRect(184, 270, 165, 36))
        self.boton_salir.setStyleSheet("background-color: rgb(237, 51, 59);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_salir.setObjectName("boton_salir")
        self.boton_mas = QtWidgets.QPushButton(Form)
        self.boton_mas.setGeometry(QtCore.QRect(12, 186, 80, 36))
        self.boton_mas.setStyleSheet("background-color: rgb(165, 29, 45);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_mas.setObjectName("boton_mas")
        self.boton_6 = QtWidgets.QPushButton(Form)
        self.boton_6.setGeometry(QtCore.QRect(184, 102, 80, 36))
        self.boton_6.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_6.setObjectName("boton_6")
        self.boton_7 = QtWidgets.QPushButton(Form)
        self.boton_7.setGeometry(QtCore.QRect(12, 144, 80, 36))
        self.boton_7.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_7.setObjectName("boton_7")
        self.boton_5 = QtWidgets.QPushButton(Form)
        self.boton_5.setGeometry(QtCore.QRect(98, 102, 80, 36))
        self.boton_5.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_5.setObjectName("boton_5")
        self.boton_igual = QtWidgets.QPushButton(Form)
        self.boton_igual.setGeometry(QtCore.QRect(269, 187, 80, 77))
        self.boton_igual.setStyleSheet("background-color: rgb(129, 61, 156);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_igual.setObjectName("boton_igual")
        self.boton_8 = QtWidgets.QPushButton(Form)
        self.boton_8.setGeometry(QtCore.QRect(98, 144, 80, 36))
        self.boton_8.setStyleSheet("background-color: rgb(28, 113, 216);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_8.setObjectName("boton_8")
        self.boton_parentesisCerrado = QtWidgets.QPushButton(Form)
        self.boton_parentesisCerrado.setGeometry(QtCore.QRect(270, 102, 80, 36))
        self.boton_parentesisCerrado.setStyleSheet("\n"
"background-color: rgb(129, 61, 156);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_parentesisCerrado.setObjectName("boton_parentesisCerrado")
        self.boton_modulo = QtWidgets.QPushButton(Form)
        self.boton_modulo.setGeometry(QtCore.QRect(98, 270, 80, 36))
        self.boton_modulo.setStyleSheet("background-color: rgb(165, 29, 45);\n"
"font: 81 italic 17pt \"Ubuntu Sans\";")
        self.boton_modulo.setObjectName("boton_modulo")
        self.boton_punto.raise_()
        self.boton_divicion.raise_()
        self.boton_4.raise_()
        self.boton_menos.raise_()
        self.boton_multiplica.raise_()
        self.boton_0.raise_()
        self.boton_salir.raise_()
        self.boton_mas.raise_()
        self.boton_6.raise_()
        self.boton_7.raise_()
        self.boton_5.raise_()
        self.boton_igual.raise_()
        self.boton_8.raise_()
        self.boton_parentesisCerrado.raise_()
        self.boton_modulo.raise_()
        self.label_2.raise_()
        self.boton_1.raise_()
        self.boton_parentesisAbierto.raise_()
        self.boton_2.raise_()
        self.boton_3.raise_()
        self.valor.raise_()
        self.boton_AC.raise_()
        self.boton_9.raise_()
        self.boton_C.raise_()

        self.retranslateUi(Form)
        self.boton_C.clicked.connect(self.valor.clear) # type: ignore
        self.boton_salir.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculadora"))
        self.boton_1.setText(_translate("Form", "1"))
        self.boton_1.setShortcut(_translate("Form", "1"))
        self.boton_parentesisAbierto.setText(_translate("Form", "("))
        self.boton_parentesisAbierto.setShortcut(_translate("Form", "("))
        self.boton_2.setText(_translate("Form", "2"))
        self.boton_2.setShortcut(_translate("Form", "2"))
        self.boton_3.setText(_translate("Form", "3"))
        self.boton_3.setShortcut(_translate("Form", "3"))
        self.boton_C.setText(_translate("Form", "c"))
        self.boton_C.setShortcut(_translate("Form", "Esc"))
        self.boton_AC.setText(_translate("Form", "AC"))
        self.boton_AC.setShortcut(_translate("Form", "Backspace"))
        self.boton_9.setText(_translate("Form", "9"))
        self.boton_9.setShortcut(_translate("Form", "9"))
        self.boton_punto.setText(_translate("Form", "."))
        self.boton_punto.setShortcut(_translate("Form", "."))
        self.boton_divicion.setText(_translate("Form", "÷"))
        self.boton_divicion.setShortcut(_translate("Form", "/"))
        self.boton_4.setText(_translate("Form", "4"))
        self.boton_4.setShortcut(_translate("Form", "4"))
        self.boton_menos.setText(_translate("Form", "-"))
        self.boton_menos.setShortcut(_translate("Form", "-"))
        self.boton_multiplica.setText(_translate("Form", "x"))
        self.boton_multiplica.setShortcut(_translate("Form", "X"))
        self.boton_0.setText(_translate("Form", "0"))
        self.boton_0.setShortcut(_translate("Form", "0"))
        self.boton_salir.setText(_translate("Form", "salir"))
        self.boton_mas.setText(_translate("Form", "+"))
        self.boton_mas.setShortcut(_translate("Form", "+"))
        self.boton_6.setText(_translate("Form", "6"))
        self.boton_6.setShortcut(_translate("Form", "6"))
        self.boton_7.setText(_translate("Form", "7"))
        self.boton_7.setShortcut(_translate("Form", "7"))
        self.boton_5.setText(_translate("Form", "5"))
        self.boton_5.setShortcut(_translate("Form", "5"))
        self.boton_igual.setText(_translate("Form", "="))
        self.boton_igual.setShortcut(_translate("Form", "="))
        self.boton_8.setText(_translate("Form", "8"))
        self.boton_8.setShortcut(_translate("Form", "8"))
        self.boton_parentesisCerrado.setText(_translate("Form", ")"))
        self.boton_parentesisCerrado.setShortcut(_translate("Form", ")"))
        self.boton_modulo.setText(_translate("Form", "%"))
        self.boton_modulo.setShortcut(_translate("Form", "%"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
